from typing import Protocol, AsyncIterable
from App.domain.repositories import UserRepositoryProtocol

class AbstractUnitOrWork(Protocol):
    users: UserRepositoryProtocol
    
    async def __aenter__(self) -> "AbstractUnitOrWork": ...
    async def __aexit__(
        self, exc_type, exc, tb
    ): ...
    async def commit(self): ...
    async def rollback(self): ...